service: default
runtime: java
env: flex

runtime_config:
  jdk: openjdk8

handlers:
- url: /.*
  script: test No need to set anything here

manual_scaling:
  instances: 1

health_check:
  enable_health_check: true